repos:
- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
    - id: yapf
      exclude: /third_party/
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
      exclude: /third_party/
