repos:
- repo: local
  hooks:
    - id: yapf
      name: yapf
      entry: yapf
      language: system
      types: [python]
      args: ["-i", "-r"]
    - id: isort
      name: isort (python)
      entry: isort
      language: system
      types: [python]
